/* This file was generated by SableCC (http://www.sablecc.org/). */

package Jalice.node;

import Jalice.analysis.*;

@SuppressWarnings("nls")
public final class TComandoInicio extends Token
{
    public TComandoInicio()
    {
        super.setText("inicio");
    }

    public TComandoInicio(int line, int pos)
    {
        super.setText("inicio");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComandoInicio(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComandoInicio(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComandoInicio text.");
    }
}
