/* This file was generated by SableCC (http://www.sablecc.org/). */

package Jalice.node;

import Jalice.analysis.*;

@SuppressWarnings("nls")
public final class TComandoFim extends Token
{
    public TComandoFim()
    {
        super.setText("fim");
    }

    public TComandoFim(int line, int pos)
    {
        super.setText("fim");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComandoFim(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComandoFim(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComandoFim text.");
    }
}
