/* This file was generated by SableCC (http://www.sablecc.org/). */

package Jalice.node;

import Jalice.analysis.*;

@SuppressWarnings("nls")
public final class TFechacomentario extends Token
{
    public TFechacomentario()
    {
        super.setText("*/");
    }

    public TFechacomentario(int line, int pos)
    {
        super.setText("*/");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFechacomentario(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFechacomentario(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFechacomentario text.");
    }
}
