/* This file was generated by SableCC (http://www.sablecc.org/). */

package Jalice.node;

import Jalice.analysis.*;

@SuppressWarnings("nls")
public final class TPVirgula extends Token
{
    public TPVirgula()
    {
        super.setText(" ; ");
    }

    public TPVirgula(int line, int pos)
    {
        super.setText(" ; ");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPVirgula(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPVirgula(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPVirgula text.");
    }
}
